name: vlad
favicon: null
layout_spectrum: 0.7043101168237627
typography_spectrum: 0.7239232659339905
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.5205698872450739
  lightness: 0.05549218808300793
  saturation: 0.4648839558940381
  rhythmicContrast: 0.6983073533046991
purpose: []
